export const Specialist = [
    {
      speciality: 'Cardiologist',
      image:
        'https://img.icons8.com/ios/150/000000/hypertension.png',
    },
    {
      speciality: 'Physician',
      image:
        "https://img.icons8.com/pastel-glyph/150/000000/doctor-skin-type-1.png",
    },
    {
        speciality:'Gynecologists',
        image:
    "https://img.icons8.com/ios/150/000000/uterus.png",
    },
    {
        speciality:'Allergists',
        image:
        "https://img.icons8.com/ios/150/000000/sneezing-in-a-tissue.png",
    },
    {
        speciality:'Orthopedic',
        image:
 "https://img.icons8.com/ios/150/000000/knee-joint.png",
    },
    {
        speciality:'Dermatologists',
        image:
        "https://img.icons8.com/ios/150/000000/skin.png",
    },
    {
        speciality:'ENT',
        image:
        "https://img.icons8.com/ios/150/000000/ear-ache.png"
    },
    {
        speciality:'Sexologist',
        image:
        "https://img.icons8.com/ios/150/000000/gender.png",
    },
    {
        speciality:'Opthalmologist',
        image:
        "https://img.icons8.com/ios/150/000000/look.png",
    },
    {
        speciality:'Paedetrician',
        image:
        "https://img.icons8.com/ios/150/000000/babys-room.png",
    },
    {
        speciality:'Neurologists',
        image:
        "https://img.icons8.com/ios/150/000000/brain.png"
    },
    {
        speciality:'Urologist',
        image:
       "https://img.icons8.com/ios/150/000000/kidney.png",
    },
    {
        speciality:'Dentist',
        image:
        "https://img.icons8.com/ios/150/000000/toothache.png",
    },
    {
        speciality:'Physiotherapist',
        image:
       "https://img.icons8.com/ios/150/000000/physical-therapy.png",
    },
    {
        speciality:'Psychiatrists',
        image:
       "https://img.icons8.com/ios/150/000000/mental-health.png",
    },


  ];
